# docker-compose.yml

version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  # backend:
  #   image: news_backend
  #   volumes:
  #     - .:/app  # 挂载当前目录到容器中的 /app 目录
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - redis
  #   environment:
  #     - DJANGO_SETTINGS_MODULE=news.settings
  #     - DEBUG=1

  vue-app:
    image: news_frontend
    ports:
      - "80:80"
  
  django_asgi:
    container_name: django_asgi
    image: news_backend
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    # command: daphne -b 0.0.0.0 -p 8000 news.asgi:application
    ports:
    - "8000:8000"
    depends_on:
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=news.settings
      - DEBUG=1
