# Generated by Django 4.2.13 on 2024-05-27 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("img_href", models.TextField()),
                ("content", models.TextField()),
                ("display", models.BooleanField(default=False)),
                ("published_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"db_table": "news", "ordering": ["id"],},
        ),
    ]
