# Generated by Django 4.2.13 on 2024-05-27 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="news_href",
            field=models.URLField(default="", unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="news", name="img_href", field=models.URLField(),
        ),
    ]
